# Generated by Django 5.2.6 on 2025-10-16 09:09

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('region', models.CharField(blank=True, max_length=50, null=True)),
                ('district', models.CharField(blank=True, max_length=50, null=True)),
                ('district_code', models.CharField(blank=True, max_length=254, null=True)),
                ('reg_code', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'district',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProtectedArea',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('reserve_na', models.CharField(blank=True, max_length=30, null=True)),
                ('region', models.CharField(blank=True, max_length=30, null=True)),
                ('area_sqkm', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'protected_area',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Studyaarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('shape_leng', models.FloatField(blank=True, null=True)),
                ('shape_area', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'studyAarea',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='trainingdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('lng', models.FloatField(blank=True, max_length=254, null=True)),
                ('lat', models.FloatField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(blank=True, choices=[('forest', 'forest'), ('urban', 'urban'), ('vegetation', 'vegetation')], max_length=15, null=True)),
                ('value', models.FloatField(blank=True, choices=[(0, 'forest'), (1, 'urban'), (2, 'vegetation')], max_length=15, null=True)),
                ('entrydate', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
